project:
  type: website

website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: coursework.qmd
        text: Academic Experience
      - href: work.qmd
        text: Work Experience
  page-footer:
    right: "&copy; 2024, John Wu"
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true


execute:
  freeze: auto
  
